---
AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Resources:

  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: golang_app_serverless
      Runtime: go1.x
      Environment:
        Variables:
          port: VALUE
      Events:
        RootEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
        PingEvent:
          Type: Api
          Properties:
            Path: /ping
            Method: get
        ExternalEvent:
          Type: Api
          Properties:
            Path: /external
            Method: get

Outputs:

  Endpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"