---
AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Resources:

  BuckFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      Environment:
        Variables:
          verificationToken: VALUE
          oauthToken: VALUE
          port: VALUE
          db: VALUE
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /buck
            Method: post
        TestEvent:
          Type: Api
          Properties:
            Path: /test
            Method: get

Outputs:

  Endpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"